function getParameterByName(name,url){if(!url)url=window.location.href;name=name.replace(/[\[\]]/g,"\\$&");var regex=new RegExp("[?&]"+name+"(=([^&#]*)|&|#|$)"),results=regex.exec(url);if(!results)return null;if(!results[2])return'';return decodeURIComponent(results[2].replace(/\+/g," "))}
function setHiddenSource(sourceParam){var parameterValue=getParameterByName(sourceParam);var parameterField="#"+sourceParam;if(parameterValue!==null&&$(parameterField).length){$(parameterField).val(parameterValue)}}
$("select[name='healthcareBusinessType']").on('change',function(){console.log('clicked business type dropdown');var busTypeValue=$("select[name='healthcareBusinessType']").val();if(busTypeValue=='Hospital'||busTypeValue=='HealthcareSystem'){$('#hospitalBedsField').css("display","block");$("select[name='hospitalBeds']").prop('required',!0).addClass("required")}else{$('#hospitalBedsField').css("display","none");$("select[name='hospitalBeds']").prop('required',!1).removeClass("required")}});function checkFields(){$('#contact-form input[type=text], #contact-form select').each(function(){var fieldName=this.getAttribute('name');var required=$(document.getElementsByName(fieldName)).hasClass('required');var email=$(document.getElementsByName(fieldName)).hasClass('email');if(this.value==''&&required){$(document.getElementsByName(fieldName)).addClass('field-error')}else{$(document.getElementsByName(fieldName)).removeClass('field-error')}
if(email){if(validateEmail(this.value)){$(document.getElementsByName(fieldName)).removeClass('field-error')}else{$(document.getElementsByName(fieldName)).addClass('field-error')}}})}
function validateEmail(email){var re=/^[_\.0-9a-zA-Z-]+@([0-9a-zA-Z][0-9a-zA-Z-]+\.)+[a-zA-Z]{2,6}$/i;return re.test(email)}
function checkFieldsInstant(element){var fieldName=element.getAttribute('name');var field=$(document.getElementsByName(fieldName));var required=$(document.getElementsByName(fieldName)).hasClass('required');var email=$(document.getElementsByName(fieldName)).hasClass('email');var phone=$(document.getElementsByName(fieldName)).hasClass('phone');var fieldLength=field.val().length;var minValue=element.getAttribute('data-min-length');if(!email&&!phone){console.log("checked regular field");if(fieldLength<1&&required){field.parent().addClass('field-error');field.parent().removeClass('field-success')}else{field.parent().removeClass('field-error');field.parent().addClass('field-success')}}
if(email){console.log("checked email");if(validateEmail(field.val())){field.parent().removeClass('field-error');field.parent().addClass('field-success')}else{field.parent().addClass('field-error');field.parent().removeClass('field-success')}}
if(phone){console.log("checked phone");if(fieldLength<8&&required){field.parent().addClass('field-error');field.parent().removeClass('field-success')}else{field.parent().removeClass('field-error');field.parent().addClass('field-success')}}}
$(document).ready(function(){var formSubmitted=!1;$.support.placeholder=(function(){var i=document.createElement('input');return'placeholder' in i})();if(!$.support.placeholder){$('#contact-form label').each(function(){$(this).addClass('js-show-label')})}
$('#contact-form').find('input').on('input change keyup blur focus',function(e){var $this=$(this);var $previous=$this.parent().prev();if(e.type=='keyup'){if($this.val()==''&&$.support.placeholder){$previous.removeClass('js-show-label')}else{$previous.addClass('js-show-label')}}
checkFieldsInstant(this)});$('#contact-form').find('select').on('input change keyup blur focus click',function(e){var $this=$(this);var $previous=$this.parent().prev();if(e.type=='click'||e.type=='keyup'){if($this.val()==''&&$.support.placeholder){$previous.removeClass('js-show-label')}else{$previous.addClass('js-show-label')}}
checkFieldsInstant(this)});setHiddenSource("utmsource");var form=$('#contact-form');var formMessages=$('#form-message');$(form).submit(function(event){var formData=$(form).serialize();$.ajax({type:'POST',url:'/admin/eloqua-submit',data:formData}).done(function(response){$('#contact-form').hide();$('.thank-you-box').removeClass("hidden");var now=new Date();var expiresDate=new Date();expiresDate.setDate(now.getDate()+365);Cookies.set('hcrevenueassurance0518','1',{expires:expiresDate});$(formMessages).removeClass('error');$(formMessages).addClass('success')}).fail(function(data){$(formMessages).removeClass('success');$(formMessages).addClass('error');if(data.responseText!==''){$(formMessages).text(data.responseText)}else{$(formMessages).text('An error occured. Please try again.')}});event.preventDefault()})});if(Cookies.get('hcrevenueassurance0518')==='1'){$('#contact-form').hide();$('.thank-you-box').removeClass("hidden")}else if(Cookies.get('hcrevenueassurance0518')==='1'){$('#contact-form').hide();$('.thank-you-box').removeClass("hidden")}